import type { Category, Localized } from './projects';

export const EMAIL = 'serignolli.software@hotmail.com';
export const LINKEDIN_URL = 'https://www.linkedin.com/in/gabriel-moreno-serignolli/';
export const GITHUB_URL = 'https://github.com/Serignolli';

/*
 * Não existe seção de apoio aqui: o pedido de apoio mora dentro de cada projeto, no
 * momento em que a ferramenta acabou de funcionar. Esta página é projetos + freelance.
 */

/**
 * O gerador que desenha o padrão do hero.
 *
 * TODO Gabriel: preencher quando o site estiver no ar. Com `url` vazia o modal continua
 * funcionando, só explica o padrão e esconde o botão de visitar, nunca aponta pra um
 * link que não existe. Os nomes dos parâmetros em `params` precisam bater com os que o
 * gerador lê na query string.
 */
export const artGenerator = {
  name: '',
  url: '',
};

/**
 * A página de currículo (`curriculo.html`, servida em `/curriculo`).
 *
 * Caminho relativo por ser do mesmo site. O link se adapta sozinho: se um dia virar
 * endereço externo, abre em aba nova.
 */
export const curriculum = {
  url: '/curriculo',
};

/**
 * Título e texto de cada grupo na página principal. Grupo sem projeto em destaque
 * não renderiza nada.
 */
export const groupContent: Record<
  Category,
  { heading: Localized; subtitle?: Localized }
> = {
  tool: {
    heading: { pt: 'Ferramentas', en: 'Tools' },
    subtitle: {
      pt: 'Faço ferramentas úteis e gratuitas, abertas pra qualquer um usar. Aqui vão algumas. Se não achou a que você precisa, me chama: dá pra gente construir ela juntos.',
      en: "I build useful, free tools that anyone can use. Here are a few. If you didn't find the one you need, reach out: we can build it together.",
    },
  },
  lab: {
    heading: { pt: 'Jogos e brincadeiras', en: 'Games & fun stuff' },
    subtitle: {
      pt: 'Nem tudo precisa ser sério. Pra divertir também faço jogos, brincadeiras e uns experimentos. Alguns exemplos:',
      en: 'Not everything has to be serious. For fun I also make games, toys and a few experiments. Some examples:',
    },
  },
  client: {
    heading: { pt: 'Exemplos', en: 'Examples' },
  },
};

/** Nome de cada faixa do catálogo (/projetos). */
export const categoryLabel: Record<Category, Localized> = {
  tool: { pt: 'Ferramentas', en: 'Tools' },
  client: { pt: 'Feitos para clientes', en: 'Built for clients' },
  lab: { pt: 'Jogos e brincadeiras', en: 'Games & fun stuff' },
};

/** Caminho do catálogo com todos os projetos publicados. */
export const CATALOG_URL = '/projetos';

export const content = {
  header: {
    name: 'Gabriel Serignolli',
    /** Quebra o nome em duas linhas no hero; a segunda parte recebe o destaque. */
    nameParts: { first: 'Gabriel', last: 'Serignolli' },
    role: { pt: 'Desenvolvedor full stack', en: 'Full stack developer' },
    tagline: {
      pt: 'Desenvolvedor full stack. Construo ferramentas úteis, alguns jogos por diversão e sistemas sob encomenda. A maior parte está aqui embaixo, aberta para qualquer um usar.',
      en: 'Full stack developer. I build useful tools, a few games for fun, and custom systems on request. Most of it is right below, free for anyone to use.',
    },
    cta: { pt: 'Fale comigo', en: 'Get in touch' },
    scroll: { pt: 'role a página', en: 'scroll down' },
  },

  nav: {
    label: { pt: 'Seções da página', en: 'Page sections' },
    home: { pt: 'Início', en: 'Home' },
    tool: { pt: 'Ferramentas', en: 'Tools' },
    freelance: { pt: 'Sob encomenda', en: 'Custom work' },
    lab: { pt: 'Jogos', en: 'Games' },
    all: { pt: 'Todos os projetos', en: 'All projects' },
    curriculum: { pt: 'Currículo', en: 'Résumé' },
    contact: { pt: 'Contato', en: 'Contact' },
  },

  language: {
    toggleLabel: {
      pt: 'Mudar idioma para inglês',
      en: 'Switch language to Portuguese',
    },
  },

  projects: {
    /** O `{name}` vem sempre de projects.ts, nunca da URL. */
    fromBanner: {
      pt: 'Você chegou pelo {name}, obrigado por usar. Estes são os outros projetos:',
      en: 'You came from {name}, thanks for using it. Here are the other projects:',
    },
  },

  art: {
    openLabel: {
      pt: 'Ver como este padrão foi gerado',
      en: 'See how this pattern was made',
    },
    heading: { pt: 'O padrão de hoje', en: "Today's pattern" },
    /** `{name}` vem de `artGenerator`, nunca da URL. */
    by: {
      pt: 'Esse padrão da imagem foi gerado pelo {name}, uma ferramenta que eu fiz.',
      en: 'This pattern was generated by {name}, a tool I built.',
    },
    bySoon: {
      pt: 'Esse padrão da imagem foi gerado por uma ferramenta que estou construindo.',
      en: "This pattern was generated by a tool I'm building.",
    },
    daily: {
      pt: 'Todo dia nasce um diferente, e este aqui vale só por hoje.',
      en: 'A different one is born every day, and this one only lasts today.',
    },
    /** `{theme}` vem de `artDates`, é sempre um texto nosso. */
    theme: {
      pt: 'Hoje ele está com tema de {theme}.',
      en: "Today it's wearing a {theme} theme.",
    },
    visit: { pt: 'Quero visitar', en: 'Take me there' },
    later: {
      pt: 'Se não quiser agora, você encontra a ferramenta aqui embaixo, nos projetos.',
      en: "If you'd rather not now, you'll find the tool right below, in the projects.",
    },
    close: { pt: 'Fechar', en: 'Close' },
  },

  /** Rótulo de cada data especial, usado no modal. */
  artDates: {
    'ano-novo': { pt: 'Ano Novo', en: 'New Year' },
    carnaval: { pt: 'Carnaval', en: 'Carnival' },
    pascoa: { pt: 'Páscoa', en: 'Easter' },
    'sao-joao': { pt: 'festa junina', en: 'Festa Junina' },
    maes: { pt: 'Dia das Mães', en: "Mother's Day" },
    pais: { pt: 'Dia dos Pais', en: "Father's Day" },
    independencia: { pt: 'Sete de Setembro', en: 'Brazilian Independence Day' },
    criancas: { pt: 'Dia das Crianças', en: "Children's Day" },
    namorados: { pt: 'Dia dos Namorados', en: "Brazilian Valentine's Day" },
    valentines: { pt: 'Dia dos Namorados americano', en: "Valentine's Day" },
    'st-patricks': { pt: 'St. Patrick', en: "St. Patrick's Day" },
    halloween: { pt: 'Halloween', en: 'Halloween' },
    thanksgiving: { pt: 'Thanksgiving', en: 'Thanksgiving' },
    natal: { pt: 'Natal', en: 'Christmas' },
  } as Record<string, Localized>,

  /** Chamada da principal para o catálogo. */
  allProjects: {
    heading: { pt: 'Quer ver tudo?', en: 'Want to see everything?' },
    text: {
      pt: 'Esses foram só alguns exemplos. No catálogo estão todos os projetos publicados, separados por categoria.',
      en: 'Those were just a few examples. The catalog has every published project, sorted by category.',
    },
    action: { pt: 'Ver todos os projetos', en: 'See all projects' },
  },

  catalog: {
    heading: { pt: 'Todos os projetos', en: 'All projects' },
    intro: {
      pt: 'Tudo que já coloquei no ar, separado por categoria: ferramentas, trabalhos para clientes e jogos.',
      en: "Everything I've shipped, sorted by category: tools, client work and games.",
    },
    count: {
      singular: { pt: 'projeto', en: 'project' },
      plural: { pt: 'projetos', en: 'projects' },
    },
    prev: { pt: 'Anteriores', en: 'Previous' },
    next: { pt: 'Próximos', en: 'Next' },
    repo: { pt: 'Código', en: 'Code' },
    cta: {
      heading: { pt: 'Não achou o que precisava?', en: "Didn't find what you need?" },
      text: {
        pt: 'Eu também desenvolvo sob encomenda. Me conta a ideia e a gente vê como tirar do papel.',
        en: 'I also build on demand. Tell me your idea and we will figure out how to make it real.',
      },
      action: { pt: 'Fale comigo', en: 'Get in touch' },
    },
  },

  badges: {
    soon: { pt: 'em breve', en: 'coming soon' },
    from: { pt: 'você veio daqui', en: 'you came from here' },
  },

  freelance: {
    heading: { pt: 'Trabalho sob encomenda', en: 'Custom work' },
    intro: {
      pt: 'Se gostou dos projetos e soluções e quer um para você, eu também trabalho sob demanda: entre em contato com a sua ideia e vamos conversar sobre.',
      en: 'If you liked these projects and want one of your own, I also work on demand: get in touch with your idea and we can talk it through.',
    },
    casesIntro: {
      pt: 'Se sente que precisa mas não sabe exatamente o que, veja alguns problemas típicos:',
      en: "If you feel you need something but aren't sure what, here are some typical problems:",
    },
    cases: [
      {
        pt: 'Uma planilha que virou gargalo e precisa virar um sistema integrado',
        en: 'A spreadsheet that became a bottleneck and needs to become an integrated system',
      },
      {
        pt: 'Um processo manual e repetitivo que dá pra automatizar',
        en: 'A manual, repetitive process that could be automated',
      },
      {
        pt: 'Dois sistemas que não conversam e precisam de uma integração',
        en: "Two systems that don't talk to each other and need an integration",
      },
      {
        pt: 'Uma ideia que já foi validada no papel e precisa existir de verdade',
        en: "An idea that's already validated on paper and needs to actually exist",
      },
    ],
    closing: {
      pt: 'Faço a parte visual, o servidor e a publicação, você não precisa montar um time nem contratar mais ninguém pra colocar no ar.',
      en: "I handle the interface, the server and the deployment, you don't need to put together a team or hire anyone else to get it live.",
    },
    pricing: {
      pt: 'Não tenho tabela fixa: me conte o que precisa e eu digo se faz sentido e quanto custa.',
      en: "No fixed price list: tell me what you need and I'll say whether it makes sense and what it would cost.",
    },
  },

  curriculum: {
    heading: { pt: 'Currículo', en: 'Résumé' },
    text: {
      pt: 'Se você prefere o formato tradicional, com formação, experiência e as tecnologias que uso no dia a dia, está tudo lá.',
      en: "If you prefer the traditional format, with education, experience and the tech I work with day to day, it's all there.",
    },
    action: { pt: 'Ver currículo completo', en: 'See the full résumé' },
  },

  contact: {
    heading: { pt: 'Fale comigo', en: 'Get in touch' },
    copy: { pt: 'copiar', en: 'copy' },
    copied: { pt: 'copiado', en: 'copied' },
    copyLabel: { pt: 'Copiar endereço de e-mail', en: 'Copy email address' },
    linkedin: { pt: 'Também estou no LinkedIn', en: "I'm also on LinkedIn" },
    github: { pt: 'e no GitHub', en: 'and on GitHub' },
  },
} as const;
